export const data = {
  text: [
    {
      observable: 'fromEvent',
      // importance: 'used for click event ',
      example: 'check it out',
      link: '/observable/event',
    },
    {
      observable: 'Interval&Time',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/interval',
    },
    {
      observable: 'of & from',
      // importance: 'gets an arrays as an observable ',
      example: 'check it out',
      link: '/observable/ofFrom',
    },
    {
      observable: 'ToArray',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/toArray',
    },
    {
      observable: 'Custom Observable',
      // importance: 'importance',
      example: 'check it out',
      link: '/observable/custom',
    },
    {
      observable: 'Map',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/map',
    },
    // {
    //   observable: 'Pluck',
    //   importance: 'importance ',
    //   example: 'check it out',
    //   link: '/observable/pluck',
    // },
    {
      observable: 'Filter',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/filter',
    },
    {
      observable: 'Tap',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/tap',
    },
    {
      observable: 'Take | TakeUntil | TakeLast',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/take',
    },
    {
      observable: 'Retry | RetryWhen | Scan & Delay',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/retry',
    },
    {
      observable: 'DebounceTime & DistinctUntilChange',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/debounceTime',
    },
    {
      observable: 'Subject & SubjectBehaviour',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/subject',
    },
    {
      observable: 'Replay Subject',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/replaySubject',
    },
    {
      observable: 'Async Subject',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/asyncSubject',
    },
    {
      observable: 'Concate and Merge',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/conMerge',
    },
    {
      observable: 'Merge Map',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/merge',
    },
    {
      observable: 'Concate Map',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/concate',
    },
    {
      observable: 'switchMap',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/switchmap',
    },
    {
      observable: 'Exhaust Map',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/exhausthmap',
    },
    {
      observable: 'shareReplay',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/share',
    },
    {
      observable: 'Combine Latest',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/combine',
    },
    {
      observable: 'Zip & Fork Join',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/join',
    },
    {
      observable: 'Catch Error & throwError',
      // importance: 'importance ',
      example: 'check it out',
      link: '/observable/error',
    },
  ],
};
